# Generated by Django 5.1.7 on 2025-11-14 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="成就名稱")),
                ("description", models.TextField(verbose_name="成就描述")),
                (
                    "achievement_type",
                    models.CharField(max_length=50, verbose_name="成就類型"),
                ),
                ("target_value", models.BigIntegerField(verbose_name="目標值")),
                (
                    "reward_coins",
                    models.IntegerField(default=0, verbose_name="獎勵金幣"),
                ),
                (
                    "icon",
                    models.CharField(default="🏆", max_length=50, verbose_name="圖標"),
                ),
            ],
            options={
                "verbose_name": "成就",
                "verbose_name_plural": "成就",
            },
        ),
        migrations.CreateModel(
            name="ShopItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="物品名稱")),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("time_extension", "遊戲時間延長"),
                            ("extra_button", "額外點擊按鈕"),
                            ("auto_clicker", "自動點擊器"),
                        ],
                        max_length=20,
                        verbose_name="物品類型",
                    ),
                ),
                ("description", models.TextField(verbose_name="描述")),
                ("base_price", models.IntegerField(verbose_name="基礎價格")),
                ("effect_value", models.FloatField(default=0, verbose_name="效果值")),
                ("max_level", models.IntegerField(default=10, verbose_name="最大等級")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "商店物品",
                "verbose_name_plural": "商店物品",
            },
        ),
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clicks", models.IntegerField(default=0, verbose_name="點擊次數")),
                (
                    "game_duration",
                    models.FloatField(default=10.0, verbose_name="遊戲時長（秒）"),
                ),
                (
                    "coins_earned",
                    models.IntegerField(default=0, verbose_name="獲得金幣"),
                ),
                (
                    "played_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="遊戲時間"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "遊戲記錄",
                "verbose_name_plural": "遊戲記錄",
                "ordering": ["-played_at"],
            },
        ),
        migrations.CreateModel(
            name="PlayerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coins", models.BigIntegerField(default=0, verbose_name="金幣")),
                (
                    "total_clicks",
                    models.BigIntegerField(default=0, verbose_name="總點擊次數"),
                ),
                (
                    "best_clicks_per_round",
                    models.IntegerField(default=0, verbose_name="單局最佳點擊次數"),
                ),
                (
                    "total_games_played",
                    models.IntegerField(default=0, verbose_name="總遊戲局數"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "玩家資料",
                "verbose_name_plural": "玩家資料",
            },
        ),
        migrations.CreateModel(
            name="PlayerAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unlocked_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="解鎖時間"),
                ),
                (
                    "reward_claimed",
                    models.BooleanField(default=False, verbose_name="獎勵已領取"),
                ),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_achievements",
                        to="game.achievement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "玩家成就",
                "verbose_name_plural": "玩家成就",
                "unique_together": {("user", "achievement")},
            },
        ),
        migrations.CreateModel(
            name="PlayerPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField(default=1, verbose_name="等級")),
                ("price_paid", models.IntegerField(verbose_name="支付價格")),
                (
                    "purchased_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="購買時間"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shop_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="game.shopitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "購買記錄",
                "verbose_name_plural": "購買記錄",
                "unique_together": {("user", "shop_item")},
            },
        ),
    ]
