# Generated by Django 5.1.7 on 2025-11-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerprofile",
            name="battle_wins",
            field=models.IntegerField(default=0, verbose_name="對戰勝場數"),
        ),
    ]
