# Generated by Django 5.1.7 on 2025-11-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_playerprofile_battle_wins"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerprofile",
            name="badge_1_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="徽章1"),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="badge_2_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="徽章2"),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="badge_3_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="徽章3"),
        ),
    ]
