# Generated by Django 5.1.7 on 2025-11-15 15:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_playerprofile_badge_1_id_playerprofile_badge_2_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamesession",
            name="played_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="遊戲時間"
            ),
        ),
        migrations.AddIndex(
            model_name="gamesession",
            index=models.Index(
                fields=["user", "-played_at"], name="game_session_user_played_idx"
            ),
        ),
    ]
