"""
Django settings for react_game project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 載入 .env.local 文件（用於本地開發）
# 如果文件不存在，不會報錯
env_local_path = BASE_DIR / '.env.local'
if env_local_path.exists():
    try:
        from dotenv import load_dotenv
        load_dotenv(env_local_path)
    except ImportError:
        # 如果 python-dotenv 未安裝，手動讀取 .env.local
        with open(env_local_path, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    os.environ.setdefault(key.strip(), value.strip())


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--n(rzjqnznjg_tn6%_i$%d3u_5)c=afx^0_b^+gy0-5@1+g802'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


if os.getenv('RENDER'):
    ALLOWED_HOSTS = ['clickfast.onrender.com']
elif os.getenv('VERCEL'):
    ALLOWED_HOSTS = ['.vercel.app']
else:
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'game',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'react_game.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'react_game.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# 使用環境變數配置資料庫，預設使用 PostgreSQL
# 開發環境可以使用 SQLite3，但生產環境必須使用 PostgreSQL

def parse_database_url(database_url):
    """解析 DATABASE_URL 連接字串"""
    try:
        # 處理 postgres:// 和 postgresql:// 兩種格式
        if database_url.startswith('postgres://'):
            database_url = database_url.replace('postgres://', 'postgresql://', 1)
        
        parsed = urlparse(database_url)
        
        return {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': parsed.path[1:] if parsed.path.startswith('/') else parsed.path,  # 移除開頭的 /
            'USER': parsed.username,
            'PASSWORD': parsed.password,
            'HOST': parsed.hostname,
            'PORT': parsed.port or '5432',
            'OPTIONS': {
                'connect_timeout': 10,
                'sslmode': 'require',  # 強制使用 SSL 連接（適用於 Supabase）
            },
            'CONN_MAX_AGE': 600,  # 連接池：保持連接 10 分鐘，減少連接開銷
        }
    except Exception as e:
        # 如果解析失敗，返回 None
        return None

if os.getenv('USE_SQLITE', '').lower() == 'true':
    # 開發環境：使用 SQLite3（僅用於本地開發）
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
elif os.getenv('DATABASE_URL'):
    # 優先使用 DATABASE_URL（適用於 Vercel、Heroku 等平台）
    database_config = parse_database_url(os.getenv('DATABASE_URL'))
    if database_config:
        DATABASES = {
            'default': database_config
        }
    else:
        # 如果解析失敗，回退到 SQLite3
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }
elif os.getenv('VERCEL'):
    # Vercel 環境：必須使用 PostgreSQL（Supabase 或其他雲端資料庫）
    # 檢查是否有設置個別資料庫環境變數
    if os.getenv('DB_HOST'):
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': os.getenv('DB_NAME', 'clickfast_db'),
                'USER': os.getenv('DB_USER', 'postgres'),
                'PASSWORD': os.getenv('DB_PASSWORD', ''),
                'HOST': os.getenv('DB_HOST'),
                'PORT': os.getenv('DB_PORT', '5432'),
                'OPTIONS': {
                    'connect_timeout': 10,
                    'sslmode': 'require',  # 強制使用 SSL 連接（適用於 Supabase）
                },
                'CONN_MAX_AGE': 600,  # 連接池：保持連接 10 分鐘，減少連接開銷
            }
        }
    else:
        # 如果沒有設置資料庫環境變數，使用 SQLite3（僅用於測試，不適合生產環境）
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }
else:
    # 其他環境（Render 等）：使用 PostgreSQL
    # 優先檢查是否有個別環境變數
    if os.getenv('DB_HOST'):
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': os.getenv('DB_NAME', 'clickfast_db'),
                'USER': os.getenv('DB_USER', 'postgres'),
                'PASSWORD': os.getenv('DB_PASSWORD', ''),
                'HOST': os.getenv('DB_HOST', 'localhost'),
                'PORT': os.getenv('DB_PORT', '5432'),
                'OPTIONS': {
                    'sslmode': 'require',  # 強制使用 SSL 連接（適用於 Supabase）
                },
                'CONN_MAX_AGE': 600,  # 連接池：保持連接 10 分鐘，減少連接開銷
            }
        }
    else:
        # 如果沒有設置，使用 SQLite3（開發環境）
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 日誌配置
# 過濾掉未登錄時的 401 警告（這是正常行為，不需要記錄為警告）
import logging

class SkipUnauthorizedFilter(logging.Filter):
    """過濾掉 /api/profile/ 的 401 未登錄警告"""
    def filter(self, record):
        # 檢查是否是 401 錯誤且路徑是 /api/profile/
        if hasattr(record, 'status_code') and record.status_code == 401:
            if hasattr(record, 'request') and hasattr(record.request, 'path'):
                if '/api/profile/' in record.request.path:
                    return False  # 過濾掉這個日誌
        return True  # 保留其他日誌

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'skip_unauthorized': {
            '()': SkipUnauthorizedFilter,
        },
    },
    'formatters': {
        'default': {
            'format': '[{asctime}] "{method} {path} HTTP/1.1" {status_code} {size}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'filters': ['skip_unauthorized'],
            'formatter': 'default',
        },
    },
    'loggers': {
        'django.server': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}